name: End-to-end tests
on:
  push:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'
      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run specific Cypress test files  
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec:
            cypress/e2e/labs/swagLabs.cy.js,
            cypress/e2e/registers/register.cy.js,
            cypress/e2e/traveloka/traveloka_hotel.cy.js

      # Upload screenshots if tests fail

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      # Always upload Cypress videos
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
